config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :welcome
  post '/geo',  to: 'welcome#geocode' 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clinica.rb
class Clinica < ApplicationRecord
    validates_presence_of :name
    validates_presence_of :address
    geocoded_by :address
    after_validation :geocode, if: :address_changed?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @clinicas = Clinica.all
  end

  def new 
    @clinicas = Clinica.new
  end

  def create
    @clinica = Clinica.new(clinica_params)
    if @clinica.save 
      clin = Clinica.last
      clin.update(name: @clinica.name, address: @clinica.address)
  
      redirect_to welcome_index_path
    else 
      render 'new'
    end    
  end

  def show 
    @clinicas = Clinica.find([:id])
  end

  def geocode
    atual = params['endereco_atual']    
    coord = Geocoder.search(atual)
    cordenadas = coord.first
    unless cordenadas.nil? 
      cordenadas = cordenadas.coordinates
    end  
    render :js => "localStorage.setItem('coordenadaAtual','#{cordenadas}');
    document.location.reload();"
  end

  private 
  def clinica_params
    params.require(:clinica).permit(:name,:address)
  end
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppEngSi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="container">
    <div class="top"> 
        <%= link_to "Oferece serviço psicológico ou psiquiátrico? Clique aqui para cadastrar sua clínica e aparecer para mais clientes!", new_welcome_url  %>
    </div>

    <h1>Encontre ajuda perto de você! </h1>

    <%= form_with(url: "/geo",method: "post") do |form| %>
        <p>
            <%= form.label :endereco_atual %>
            <%= form.text_field :endereco_atual %>
        </p>
        <p>
            <%#= form.submit "limpar", :type => "reset" %>
            <%= form.submit :Encontrar, :name=>"salvar", class: 'salvar'%> 
        </p>
    <% end %>

    <table>
    <% @clinicas.each do |c| %>
        <tr class="container">
            <td class="name"><%= c.name %></td>
            <td class="address"><%= c.address %></td>
        </tr>
        <br>
    <% end %>
    </table>

    <div id="map" data-test-env="<%= Rails.env.test? %>"></div>

    <script>
        function initMap() {
            var x = localStorage.getItem('coordenadaAtual')                         
            var coordenadaAtual= x ? JSON.parse(x) : null

            var latLng = null
            if (coordenadaAtual){
                latLng= new google.maps.LatLng(coordenadaAtual[0],coordenadaAtual[1])
            }

            var each = {lat: -23.4823919,lng:-46.5004498}

            window.map = new google.maps.Map(
                document.getElementById('map'), {zoom: 18, center: latLng ? latLng :each});  
            var mapa = document.getElementById('map')
            var opt = !(mapa.getAttribute('data-test-env')) 
            //a propriedade optmized eh setada como false para ambiente de testes
            //cria o marker como elemento unico na DOM        

            <% @clinicas.each do |c| %>
                var lat = <%= c.latitude %>;
                var longitude = <%= c.longitude %>;
                var marker = new google.maps.Marker({
                    position: {lat:  <%= c.latitude %>, lng:  <%= c.longitude %>},
                    map: map,
                    optimized: !opt
                });
            <% end %>
            
            if (coordenadaAtual){
                var origem = new google.maps.LatLng(coordenadaAtual[0],coordenadaAtual[1]);
            }
            var destinos = [];

            <% @clinicas.each do |c| %>
                var lat = <%= c.latitude %>;
                var longitude = <%= c.longitude %>;
                var destino = new google.maps.LatLng(lat, longitude);
                destinos.push(destino);
            <% end %>

            if (coordenadaAtual){
                var matrizDistancia = new google.maps.DistanceMatrixService();
                var a = matrizDistancia.getDistanceMatrix ({
                    origins: [origem],
                    destinations: destinos,
                    travelMode: 'DRIVING'
                }, encontrarMaisProximo);
            }
        }

        function encontrarMaisProximo(response, status) {
            if (status == 'OK') {
                var origins = response.originAddresses;
                var destinations = response.destinationAddresses;

                for (var i = 0; i < origins.length; i++) {
                    var results = response.rows[i].elements;
                    for (var j = 0; j < results.length; j++) {
                        var element = results[j];
                        var distance = element.distance.text;
                        var duration = element.duration.text;
                        var from = origins[i];
                        var to = destinations[j];
                    }
                }
                var distancia = results[0].distance.value;
                var count = 0;

                for (var i = 0; i < results.length; i++) {
                  var dist = results[i].distance.value;
                  if (dist < distancia) {
                      distancia = dist;
                      count = i;
                  }
                }

                var resultado = document.createElement("div");
                resultado.setAttribute("id", "clinicaProxima");

                var texto = document.createTextNode("A clínica mais próxima do seu endereço é: " + response.destinationAddresses[count]);
                resultado.appendChild(texto);

                var texto2 = document.getElementById("#localizacaoAtual");                
                document.body.insertBefore(resultado, texto2);
            }
        } 

        var coordAtual = localStorage.getItem('coordenadaAtual')

        if (coordAtual){
            document.getElementById("localizacaoAtual").innerHTML = "Localizacao Salva"
        } else{
            document.getElementById("localizacaoAtual").innerHTML = "Localizacao Não Salva"
        }                       
    </script>

    <script defer
        src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['MAPS_API_KEY']%>&callback=initMap">
    </script>
</div>

app/views/welcome/new.html.erb
<%= form_with scope: :clinica, url: "/welcome", local: true do |form|%>

          <p>
         <%= form.label :name %>
         <%= form.text_field :name %>
         </p>
         <p>
         <%= form.label :address %>
         <%= form.text_field :address %>
         </p>
         <p>
         <%= form.submit 'salvar nova clinica' %>
         </p>
     <% end %> 